### ISSUE TITLE
Jest CLI test is failing -- possibly resolver test code issue

### ISSUE THREAD

**Issue by shigeya** [w3c/did-test-suite#111]
Running jest (`npm run test`) on the current head of the `main` branch produces a lot of errors.

While there is at least a minor issue in PR #96 (one file is missing), currently,
- all of the implementation JSON files are from the PR#96
- all of the resolving tests are failing

There might be some issue with the resolver testing code. 
@peacekeeper Since you're the implementer of the test code, would you please kindly check the reason why they're failing?
since `universal-resolver-did-factom.json` is missing, you need to remove the following line in `did-resolution/default.js`.

> //    require('../implementations/universal-resolver-did-factom.json'), -- MISSING

I created PR #110 for a temporary workaround.

**Comment by BernhardFuchs** [comment]
Sorry for breaking the imports by referencing a not existing file. Actually the `did:factom` method is not working atm and should not be included in the `default.js` file. So the quick fix for everybody is to remove this line.  
We did some changes the process of creating the files/imports for the testsuite which should fix and avoid those kind of issues.

There are also some changes to the Universal Resolver which will fix test failures but we won't be able to have a 100% green testsuite atm.

By the end of the week, I will create a PR will all the changes.

**Comment by BernhardFuchs** [comment]
I've opened https://github.com/w3c/did-test-suite/pull/114 which should fix most issues.  
There are still ~15 tests failing with 4 of them related to the Universal Resolver and one of its drivers https://github.com/decentralized-identity/uni-resolver-driver-did-ccp/issues/5

**Comment by BernhardFuchs** [comment]
After disabling `resolver-ethr-consensys-mesh.json` (which is alos the case on main), the failing tests are down to 7 across the whole test-suite with #114

**Comment by msporny** [comment]
This has now been fixed, we put broken implementations in their own grouping (but do run these when generating the final report).
