### ISSUE TITLE
Top level index.html is gone

### ISSUE THREAD

**Issue by shigeya** [w3c/did-test-suite#137]
Merging the PR #120 removing top level `index.html` file and test data JSON file.

For reporting purposes, the report generator relies on the index.html as a template.

If the removal of the file at the top level is an accident, I will add it with the latest result.

If the removal is intentional, I will create a template file, and also will commit the latest test result (for reporting purposes, not for implementers to do) in a subdirectory, maybe, `packages/did-core-test-server/latest_report`.

Any suggestions?

**Comment by msporny** [comment]
> If the removal is intentional, I will create a template file, and also will commit the latest test result (for reporting purposes, not for implementers to do) in a subdirectory, maybe, `packages/did-core-test-server/latest_report`.

Yes, please do this -- add a template file.

**Comment by shigeya** [comment]
I read this after commenting on the other issue.

Then, where is the file generated, and the name of the file? index.html at the root of the repository is ok?

**Comment by shigeya** [comment]
Understood the situation and addressed it in PR #138. closing.
