### ISSUE TITLE
Is it possible to change width of the report?

### ISSUE THREAD

**Issue by shigeya** [w3c/did-test-suite#151]
I'm working on the final adjustment of the report, including what to be on the table, links between tables, etc.

Now, I realize that... I'm using a 16x9 display but I'm not making use of the rich widescreen real estate.

The current style parameter on page width for the W3C docs is 50em. This design comes from [base.css](https://www.w3.org/StyleSheets/TR/2016/base.css).

Since the report has tables with a lot of parameters, it is easier to observe the situation if we can make use of space.
Isn't it possible to make the table wider than 90em? Then, it is far easier to glance at the report.

Maybe, @iherman knows the possibility?

**Comment by TallTed** [comment]
@iherman @msporny @burnburn @brentzundel -- This seems important to answer soon, given timing on CRs, and need for implementation reports for next transition request.

**Comment by iherman** [comment]
The implementation report is not an official /TR document. As a consequence, I do not see any problem modifying the style if that makes the document more readable.

**Comment by shigeya** [comment]
@iherman Thank you.

I think we can close this issue now.

> @iherman @msporny @burnburn @brentzundel -- This seems important to answer soon, given timing on CRs, and need for implementation reports for next transition request.

Any suggestions to the table format (what to appear in the table, etc.) are welcome.

**Comment by shigeya** [comment]
Implemented with PR #175. Closing this issue.
