### ISSUE TITLE
Test Suite reporting broken with removal of Examples implementation

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#152]
@shigeya, I think a recent modification that you made to the test suite has broken the test suite reporting. 

Namely, you removed the Example implementation. We cannot do that. The example implementation is the only implementation that exercises some of the feature tests (like JSON production for integers). If a test is not exercised, it does not show up in the reports and therefore does not show up in the tallies.

You will note that the most recent test report says nothing about the JSON production features related to datetime, integer, and double. <-- that is really bad because those are completely unimplemented features.

Please add the example implementations back into the report generation (but ignore them when displaying/tallying). There may be a better way to solve this problem, but we were depending on the example implementations to at least trigger every completely unimplemented feature in the specification.

**Comment by shigeya** [comment]
Reverted in PR  #153.  This was the first commit in the last PR and I forget to discuss this. My aplogies.

**Comment by msporny** [comment]
> Reverted in PR #153. This was the first commit in the last PR and I forget to discuss this. My aplogies.

No problem @shigeya -- thank you for all of your hard work. I love the new "implementations by feature" summary!

**Comment by msporny** [comment]
I have now confirmed that everything is working again, closing.
