### ISSUE TITLE
Tests are confusing, consider refactoring

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#17]
I have improved on the initial approach taken here, in https://github.com/transmute-industries/vc.transmute.world

I am currently hosting a test server, which can be used to run the tests, their interfaces are substantially simpler:

https://github.com/transmute-industries/vc.transmute.world/blob/master/packages/jest-test-server/suites/issuer-api/issuer-api.spec.js

If its desired, I can refactor this repo to support this pattern AND host a version fo the suite that can be used to request tests on demand.

**Comment by peacekeeper** [comment]
I think this would make sense. Even though I have spent quite some time trying to contribute to this test suite (see https://github.com/w3c/did-test-suite/pull/12), it's still not entirely clear to me how it can be used against an actual implementation.

With the earlier VC HTTP API test suite you built, both extending the test suite, and testing a concrete implementation felt much simpler.

(That's my subjective view as someone who's not really a JavaScript person...)

**Comment by OR13** [comment]
refactoring complete, closing
