### ISSUE TITLE
Symbols are confusing

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-test-suite#194]
In the implementation report, all normative statements are shown to be passing with green check marks except for [specification statement 3.2.2](https://w3c.github.io/did-test-suite/#T8) which has yellow triangles, but no mention is made in the document what this means.

It is clear that green check marks are good, and red x's are bad, but what does the yellow triangle mean? Is specification statement 3.2.2 implemented or not?

@shigeya @OR13 @msporny

**Comment by msporny** [comment]
> It is clear that green check marks are good, and red x's are bad, but what does the yellow triangle mean? Is specification statement 3.2.2 implemented or not?

I believe that is a feature that @shigeya added... and I don't know what it means. :)

**Comment by shigeya** [comment]
The mark only appears when the test case is `todo`. 

For the `3.2.2`, this line is the cause:

https://github.com/w3c/did-test-suite/blob/29b5c783ca07696acd308e410bbe1837179cbe3c/packages/did-core-test-server/suites/did-url-dereferencing/did-url-dereferencing.js#L17

As with other non-testable statements, we can safely remove this line.

It's the only test line with `todo` in the entire test code (checked).

As I remember, I'm not the person who picked the emoji. Maybe we want to use a different one.

**Comment by msporny** [comment]
> It's the only test line with todo in the entire test code (checked).

Ah, I see. We shouldn't have "TODO" at this point, we can safely remove that todo.

**Comment by brentzundel** [comment]
Raised PR #196 to address this.

**Comment by peacekeeper** [comment]
> As with other non-testable statements,

Hmm is this really untestable..?

**Comment by brentzundel** [comment]
For now, I think the best thing to do is remove the `todo` line, because it results in some confusion in the implementation report.

Then someone can write a test for it, if they determine that the statement is in fact testable.
