### ISSUE TITLE
rename master branch

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-test-suite#2]
# Summary
We should rename the branch `master` to `main` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on master/slave terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `main`)

## Technical Steps

- [ ]  create main branch from master
- [ ]  make main the default GitHub branch
- [ ]  modify github/central to use main for release notes reloading
- [ ]  redirect PRs to main in w3c/did-test-suite
- [ ]  move branch protections from master to main
- [ ]  modify docs to reference main instead of master
- [ ]  delete master branch to avoid confusion?

Feedback?

**Comment by selfissued** [comment]
Please no.  This wouldn't just affect the primary repository.  This would affect every branch, every fork, and every local clone, requiring manual steps by all participants to make parallel changes to these copies.  The chances of everyone getting this right are close to zero.

Using git correctly is already complicated enough.  Please don't make this repository even more complicated than usual.

**Comment by OR13** [comment]
Its possible for us to do this, but I'm not going to unless directed to by chairs.

if we do it here, we should do it everywhere, at the same time...

IMO we should not do this, we already have enough problems with ECHIDNA / respec hosting...

however, if we are required to implement this change, we can only really do so when there are no PRs open.

so sooner rather than later on this decision would be good. @brentzundel @burnburn .

**Comment by brentzundel** [comment]
A conversation is ongoing here: https://github.com/w3c/did-core/issues/332
GitHub and the W3C are both moving forward with plans to make this change simpler, but to my understanding they are not ready yet.

**Comment by msporny** [comment]
> GitHub and the W3C are both moving forward with plans to make this change simpler, but to my understanding they are not ready yet.

I can do this in like 5 minutes... it's easy. I'll bring it up on the call today, there's no good reason for us to just not move to `main` now.

**Comment by iherman** [comment]
Done on 2021-03-25.
