### ISSUE TITLE
Need test for Conforming Producer

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#24]
6.1 Production and Consumption - A conforming producer MUST take a DID document data model and a representation-specific entries map as input into the production process. The conforming producer MAY accept additional options as input into the production process.

6.1 Production and Consumption - A conforming producer MUST serialize all entries in the DID document data model, and the representation-specific entries map, that do not have explicit processing rules for the representation being produced using only the representation's data type processing rules and return the serialization after the production process completes.

6.1 Production and Consumption - A conforming producer MUST return the Media Type string associated with the representation after the production process completes.

6.1 Production and Consumption -  A conforming producer MUST NOT produce non-conforming DIDs or DID documents.

**Comment by msporny** [comment]
PR #41 has been raised to address this issue. This issue should be closed once that PR has been merged.

**Comment by peacekeeper** [comment]
The normative statements listed in this issue need to be updated to match what's in the CR spec now (especially section 6.1):

https://www.w3.org/TR/2021/CR-did-core-20210318/#production-and-consumption

**Comment by msporny** [comment]
> The normative statements listed in this issue need to be updated to match what's in the CR spec now (especially section 6.1):
> 
> https://www.w3.org/TR/2021/CR-did-core-20210318/#production-and-consumption

I have just updated the normative statements for this issue to match what's in the spec.

**Comment by msporny** [comment]
This has been done, but needs refinement. The refinement is being tracked in #48, continuing there.
