### ISSUE TITLE
Need tests for Conforming Consumer

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#25]
6.1 Production and Consumption - A conforming consumer MUST take a representation and Media Type string as input into the consumption process. A conforming consumer MAY accept additional options as input into the consumption process.

6.1 Production and Consumption - A conforming consumer MUST determine the representation of a DID document using the Media Type input string.

6.1 Production and Consumption - A conforming consumer MUST detect any representation-specific entry across all known representations and place the entry into a representation-specific entries map which is returned after the consumption process completes. A list of all known representation-specific entries is available in the DID Specification Registries [DID-SPEC-REGISTRIES].

6.1 Production and Consumption - A conforming consumer MUST add all non-representation-specific entries that do not have explicit processing rules for the representation being consumed to the DID document data model using only the representation's data type processing rules and return the DID document data model after the consumption process completes.

6.1 Production and Consumption - A conforming consumer MUST produce errors when consuming non-conforming DIDs or DID documents.

**Comment by wyc** [comment]
@clehner will be implementing this on behalf of Spruce.

**Comment by wyc** [comment]
@clehner will be implementing this on behalf of @sprucesystems.

**Comment by peacekeeper** [comment]
The normative statements listed in this issue need to be updated to match what's in the CR spec now (especially section 6.1):

https://www.w3.org/TR/2021/CR-did-core-20210318/#production-and-consumption

**Comment by msporny** [comment]
> The normative statements listed in this issue need to be updated to match what's in the CR spec now (especially section 6.1):
> 
> https://www.w3.org/TR/2021/CR-did-core-20210318/#production-and-consumption

I have just updated the normative statements for this issue to match what's in the spec.
