### ISSUE TITLE
Need tests for DID Resolution

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#29]
[7. Resolution \
](https://w3c.github.io/did-core/#resolution)All conformant [DID resolvers](https://w3c.github.io/did-core/#dfn-did-resolvers) _MUST_ implement the [DID resolution](https://w3c.github.io/did-core/#dfn-did-resolution) functions for at least one [DID method](https://w3c.github.io/did-core/#dfn-did-methods) and _MUST_ be able to return a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) in at least one conformant [representation](https://w3c.github.io/did-core/#dfn-representations).

[7.1 DID Resolution \
](https://w3c.github.io/did-core/#did-resolution)did - This is the [DID](https://w3c.github.io/did-core/#dfn-decentralized-identifiers) to resolve. This input is _REQUIRED_ and the value _MUST_ be a conformant [DID](https://w3c.github.io/did-core/#dfn-decentralized-identifiers) as defined in [§ 3.1 DID Syntax](https://w3c.github.io/did-core/#did-syntax).

resolutionOptions - A [metadata structure](https://w3c.github.io/did-core/#metadata-structure) containing properties defined in [§ 7.1.1 DID Resolution Options](https://w3c.github.io/did-core/#did-resolution-options). This input is _REQUIRED_, but the structure _MAY_ be empty.

didResolutionMetadata - A [metadata structure](https://w3c.github.io/did-core/#metadata-structure) consisting of values relating to the results of the [DID resolution](https://w3c.github.io/did-core/#dfn-did-resolution) process which typically changes between invocations of the `resolve` and `resolveRepresentation` functions, as it represents data about the resolution process itself. This structure is _REQUIRED_, and in the case of an error in the resolution process, this _MUST NOT_ be empty. 

If `resolveRepresentation` was called, this structure _MUST_ contain a `contentType` property containing the Media Type of the representation found in the `didDocumentStream`. 

If the resolution is not successful, this structure _MUST_ contain an `error` property describing the error.

didDocument - If the resolution is successful, and if the `resolve` function was called, this _MUST_ be a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) abstract data model (a [map](https://infra.spec.whatwg.org/#maps)) as described in [§ 4. Data Model](https://w3c.github.io/did-core/#data-model) that is capable of being transformed into a [conforming DID Document](https://w3c.github.io/did-core/#dfn-conforming-did-document) (representation), using the production rules specified by the representation. 

The value of <code>[id](https://w3c.github.io/did-core/#dfn-id)</code> in the resolved [DID document](https://w3c.github.io/did-core/#dfn-did-documents) <em>MUST</em> match the [DID](https://w3c.github.io/did-core/#dfn-decentralized-identifiers) that was resolved. 

If the resolution is unsuccessful, this value _MUST_ be empty.

didDocumentStream - If the resolution is successful, and if the `resolveRepresentation` function was called, this _MUST_ be a byte stream of the resolved [DID document](https://w3c.github.io/did-core/#dfn-did-documents) in one of the conformant [representations](https://w3c.github.io/did-core/#representations). 

If the resolution is unsuccessful, this value _MUST_ be an empty stream.

didDocumentMetadata - If the resolution is successful, this _MUST_ be a [metadata structure](https://w3c.github.io/did-core/#metadata-structure).

If the resolution is unsuccessful, this output _MUST_ be an empty [metadata structure](https://w3c.github.io/did-core/#metadata-structure). 

[7.1.1 DID Resolution Options \
](https://w3c.github.io/did-core/#did-resolution-options)accept - The Media Type _MUST_ be expressed as an [ASCII string](https://infra.spec.whatwg.org/#ascii-string). 

This property is _OPTIONAL_ for the `resolveRepresentation` function and _MUST NOT_ be used with the `resolve` function.

[7.1.2 DID Resolution Metadata \
](https://w3c.github.io/did-core/#did-resolution-metadata)contentType - The Media Type of the returned `didDocumentStream`. This property is _REQUIRED_ if resolution is successful and if the `resolveRepresentation` function was called. 

This property _MUST NOT_ be present if the `resolve` function was called. 

The value of this property _MUST_ be an [ASCII string](https://infra.spec.whatwg.org/#ascii-string) that is the Media Type of the conformant [representations](https://w3c.github.io/did-core/#dfn-representations). 

The caller of the `resolveRepresentation` function _MUST_ use this value when determining how to parse and process the `didDocumentStream` returned by this function into the [data model](https://w3c.github.io/did-core/#data-model).

error - The error code from the resolution process. This property is _REQUIRED_ when there is an error in the resolution process. 

The value of this property _MUST_ be a single keyword [ASCII string](https://infra.spec.whatwg.org/#ascii-string). 

**invalidDid \
**The [DID](https://w3c.github.io/did-core/#dfn-decentralized-identifiers) supplied to the [DID resolution](https://w3c.github.io/did-core/#dfn-did-resolution) function does not conform to valid syntax. (See [§ 3.1 DID Syntax](https://w3c.github.io/did-core/#did-syntax).) \
**notFound \
**The [DID resolver](https://w3c.github.io/did-core/#dfn-did-resolvers) was unable to find the [DID document](https://w3c.github.io/did-core/#dfn-did-documents) resulting from this resolution request. \
**representationNotSupported \
**This error code is returned if the [representation](https://w3c.github.io/did-core/#dfn-representations) requested via the `accept` input metadata property is not supported by the [DID method](https://w3c.github.io/did-core/#dfn-did-methods) and/or [DID resolver](https://w3c.github.io/did-core/#dfn-did-resolvers) implementation. \

[7.1.3 DID Document Metadata \
](https://w3c.github.io/did-core/#did-document-metadata)The possible properties within this structure and their possible values _SHOULD_ be registered in the DID Specification Registries [[DID-SPEC-REGISTRIES](https://w3c.github.io/did-core/#bib-did-spec-registries)]. This specification defines the following common properties.

[7.1.3 DID Document Metadata \
](https://w3c.github.io/did-core/#did-document-metadata)created - The value of the property _MUST_ be a [string](https://infra.spec.whatwg.org/#string) formatted as an [XML Datetime](https://www.w3.org/TR/xmlschema11-2/#dateTime) normalized to UTC 00:00:00 and without sub-second decimal precision. For example: `2020-12-20T19:17:47Z`.

updated - The value of the property _MUST_ follow the same formatting rules as the `created` property. 

deactivated - If a DID has been deactivated, DID document metadata _MUST_ include this property with the boolean value `true`. If a DID has not been deactivated, this property is _OPTIONAL_, but if included, _MUST_ have the boolean value `false`. 

nextUpdate - The value of the property _MUST_ follow the same formatting rules as the `created` property. 

versionId - The value of the property _MUST_ be an [ASCII string](https://infra.spec.whatwg.org/#ascii-string).

nextVersionId - The value of the property _MUST_ be an [ASCII string](https://infra.spec.whatwg.org/#ascii-string).

The value of `equivalentId` _MUST_ be a [set](https://infra.spec.whatwg.org/#ordered-set) where each item in the list is a [string](https://infra.spec.whatwg.org/#string) that conforms to the rules in Section [§ 3.1 DID Syntax](https://w3c.github.io/did-core/#did-syntax). Each equivalentId DID value _MUST_ be produced by, and a form of, the same [DID Method](https://www.w3.org/TR/2021/CR-did-core-20210318/#dfn-did-methods) as the _id_ property value.

A conforming [DID Method](https://www.w3.org/TR/2021/CR-did-core-20210318/#dfn-did-methods) specification _MUST_ guarantee that each `equivalentId` value is logically equivalent to the `id` property value. 

`equivalentId` is a much stronger form of equivalence than `alsoKnownAs` because the equivalence _MUST_ be guaranteed by the governing [DID method](https://www.w3.org/TR/2021/CR-did-core-20210318/#dfn-did-methods).

The value of <code>[canonicalId](https://w3c.github.io/did-core/#dfn-canonicalid)</code> <em>MUST</em> be a [string](https://infra.spec.whatwg.org/#string) that conforms to the rules in Section [§ 3.1 DID Syntax](https://w3c.github.io/did-core/#did-syntax). A `canonicalId` value _MUST_ be produced by, and a form of, the same  [DID Method](https://www.w3.org/TR/2021/CR-did-core-20210318/#dfn-did-methods) as the `id` property value.

A conforming [DID Method](https://www.w3.org/TR/2021/CR-did-core-20210318/#dfn-did-methods) specification _MUST_ guarantee that the `canonicalId` value is logically equivalent to the `id` property value.

**Comment by peacekeeper** [comment]
@msporny I edited your initial comment to reflect the latest version of the spec.
