### ISSUE TITLE
Need tests for DID URL Dereferencing

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#30]
[7.2 DID URL Dereferencing \
](https://w3c.github.io/did-core/#did-url-dereferencing)didUrl - A conformant [DID URL](https://w3c.github.io/did-core/#dfn-did-urls) as a single [string](https://infra.spec.whatwg.org/#string). This is the [DID URL](https://w3c.github.io/did-core/#dfn-did-urls) to dereference. To dereference a [DID fragment](https://w3c.github.io/did-core/#dfn-did-fragments), the complete [DID URL](https://w3c.github.io/did-core/#dfn-did-urls) including the [DID fragment](https://w3c.github.io/did-core/#dfn-did-fragments) _MUST_ be used. This input is _REQUIRED_.

dereferencingOptions - This input is _REQUIRED_, but the structure _MAY_ be empty.

dereferencingMetadata - This structure is _REQUIRED_ and in the case of an error in the dereferencing process, this _MUST NOT_ be empty.

If the dereferencing is not successful, this structure _MUST_ contain an `error` property describing the error.

contentStream - If the `dereferencing` function was called and successful, this _MUST_ contain a [resource](https://w3c.github.io/did-core/#dfn-resources) corresponding to the [DID URL](https://w3c.github.io/did-core/#dfn-did-urls). 

If the dereferencing is unsuccessful, this value _MUST_ be empty.

contentMetadata - If the dereferencing is successful, this _MUST_ be a [metadata structure](https://w3c.github.io/did-core/metadata-structure), but the structure _MAY_ be empty. 

If the `contentStream` is a [DID document](https://w3c.github.io/did-core/#dfn-did-documents), this _MUST_ be a [didDocumentMetadata](https://w3c.github.io/did-core/#dfn-diddocumentmetadata) structure as described in [DID Resolution](https://w3c.github.io/did-core/#dfn-did-resolution). 

If the dereferencing is unsuccessful, this output _MUST_ be an empty [metadata structure](https://w3c.github.io/did-core/metadata-structure).

accept - The Media Type that the caller prefers for `contentStream`. The Media Type _MUST_ be expressed as an [ASCII string](https://infra.spec.whatwg.org/#ascii-string).

contentType - The Media Type value _MUST_ be expressed as an [ASCII string](https://infra.spec.whatwg.org/#ascii-string).

error - This property is _REQUIRED_ when there is an error in the dereferencing process. 

The value of this property _MUST_ be a single keyword expressed as an [ASCII string](https://infra.spec.whatwg.org/#ascii-string). This specification defines the following common error values: invalidDidUrl, notFound** \
**

**Comment by peacekeeper** [comment]
@msporny I edited your initial comment to reflect the latest version of the spec.
