### ISSUE TITLE
PROPOSAL: The test suite structured input will be in yaml and structured output will be in json 

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#4]
yaml is easy to read
json is easy to transform for rendering in web pages.

**Comment by iherman** [comment]
> yaml is easy to read

Is this a valid argument? The 'input' is to be read by a machine, after all, not for humans.

> json is easy to transform for rendering in web pages.

json is _a bit_ easier but not much; at least in node the javascript yaml parsers offer the same interface as the built-in json parser.

I guess what bothers me is the asymmetry. I do not have strong feeling on choosing between json or yaml (both are o.k. as far as I am concerned), but I would think the input and output formats should be the same.

**Comment by OR13** [comment]
sure, both could be JSON. I'd be fine with that.

**Comment by OR13** [comment]
RESOLVED: Both should be JSON.
