### ISSUE TITLE
PROPOSAL: the test suite will support strings first and callback second.

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#5]
Because callback tests are complex to implement, they should be tackled after we have tackled strings.

This means we don't need to worry about "integrations with external systems / blockchains / libraries" at the start... but we can tackle support for them _after_ we have shown the simple strings versions to be providing the kind of coverage we need.

**Comment by peacekeeper** [comment]
+1 to doing the test suite without direct integrations first. But the test suite should still be executed against data that was generated by an external implementation/library that is to be tested. I.e. testing should work like this:

1. Execute the implementation/library in some way, providing certain inputs.
2. The inputs and outputs from step 1 are sent to the test server, which runs asserations against those inputs and outputs.
