### ISSUE TITLE
jest-did-matcher not published

### ISSUE THREAD

**Issue by BernhardFuchs** [w3c/did-test-suite#69]
I'm aware that this is still work in progress but I'm experimenting to integrate this test-suite to a CI process and would like to deploy it as a standalone server.  

Running `npm install` or building the docker image for `did-core-test-server` (which does the same) fails with `'jest-did-matcher@^0.0.1' is not in the npm registry`.  

Is there a plan to publish `jest-did-matcher` to the npm registry anytime soon?

**Comment by shigeya** [comment]
It is intentionally not published and locally referenced. I was not aware of the issues. Will look into the issues. thanks.

**Comment by shigeya** [comment]
@OR13 I want to hear your opinion. As a solution to this issue, in PR #70, I tweaked Dockerfile and docker-compose to include both packages.

I don't like to see babel to create `./dist` in the image, but I couldn't find a solution.  It may be cleaner to separately publish package, but then, we have to manage two separate repositories.

Which do you prefer?

**Comment by OR13** [comment]
@shigeya its very common to publish multiple npm packages from the same repo with lerna / yarn...

- https://github.com/transmute-industries/did-core/tree/main/packages
- https://github.com/vuejs/vue/tree/dev/packages
- https://github.com/facebook/react/tree/master/packages

However, these approaches generally assume some burden on the maintainers... 

I would be happy to take `jest-did-matcher` -> `@did-core/jest-did-matcher` , here:

https://github.com/transmute-industries/did-core/tree/main/packages

I think for now, its better to keep everything unpublished and linked with lerna where it is.

**Comment by shigeya** [comment]
@OR13 I see. Then, let's keep the package stay in the local repository. Then, Is PR #70 reasonable?

**Comment by shigeya** [comment]
@BernhardFuchs We changed `jest-did-matcher` to be included as part of the docker image (see PR #70 for the changes). Would you please test and confirm it's working for you?

**Comment by BernhardFuchs** [comment]
@shigeya Thx for the quick fix. The Dockerfile works now and the image is deployable. Closing this.
