### ISSUE TITLE
Validate command cli 

### ISSUE THREAD

**Issue by gspmishra** [w3c/did-test-suite#7]
While implementation of validate command on the cli application what should the logic be. As in the README file it is not clearly mentioned.

**Comment by OR13** [comment]
I am not sure how we will align the CLI with the test suite, but I expect we will address this soon.

**Comment by OR13** [comment]
The CLI commands are no longer relevant, see the readme for the latest instructions. closing this, but feel free to open an new issues if you have trouble.
