### ISSUE TITLE
Fix did:3 resolver implementation

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-test-suite#90]
@oed you added a resolver implementation for `did:3` in https://github.com/w3c/did-test-suite/pull/57, and it was temporarily disabled in https://github.com/w3c/did-test-suite/commit/c1380272e930c174e75f2216b6ebf529ead299bb, since a number of tests are failing.

Some things to consider that are currently causing tests to fail on your implementation:

- **DID Core says in section "7. Resolution":** _"All conformant DID resolvers MUST implement the DID resolution functions for at least one DID method and MUST be able to return a DID document in at least one conformant representation"_.

--> If your implementation results only contain the "resolve" function, but not the "resolveRepresentation" function, then this test will fail.

- **DID Core says in section "7.1.2 DID Resolution Metadata" about "contentType":** _"This property MUST NOT be present if the resolve function was called."_

--> If your implementation results include the "contentType" DID resolution metadata property for the "resolve" function, then this test will fail. This also causes a number of additional test failures.

- **DID Core says in section "7.1 DID Resolution" about "did":** _"This input is REQUIRED and the value MUST be a conformant DID as defined in § 3.1 DID Syntax."_

--> If your implementation has something other than a plain DID (e.g. a DID URL with parameters) as input to the "resolve" or "resolveRepresentation" function, then this test will fail. In this case, you should probably consider the dereferencer test suite, not the resolver test suite.

Hope this helps. The [example implementation reports](https://github.com/w3c/did-test-suite/tree/main/packages/did-core-test-server/suites/implementations) may also clarify this further. Thanks for your efforts to submit an implementation report! Feel free to reply here if you need more help.

**Comment by oed** [comment]
Thanks @peacekeeper will update these. Any pointers to how the tests changed? Since these tests were passing before.

**Comment by peacekeeper** [comment]
@oed The test suite was simply not complete yet at the time you submitted your report.
